FROM maven:3.8.1-jdk-8
WORKDIR /backend

COPY . .

RUN mvn clean package
ARG JAR_FILE=./target/sopoong_backend-0.0.1-SNAPSHOT.jar
RUN cd target
COPY sopoong_backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]