FROM maven:3.8.1-jdk-8
WORKDIR /backend

COPY . .

RUN mvn clean package
ARG JAR_FILE=./target/sopoong_backend-0.0.1-SNAPSHOT.jar
RUN ls -a
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]